; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Fri Jan 30 2026 19:53:04 GMT-0800 (Pacific Standard Time)

; home Z
G91 ; relative positioning
var maxTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G1 H1 Z{-var.maxTravel} F200 ; coarse home in the -Z direction
G1 Z5 F200 ; move back 5mm
G1 H1 Z{-var.maxTravel} F100 ; fine home in the -Z direction
G90 ; absolute positioning

M98 P"posz.g"
