; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Fri Jan 30 2026 19:53:04 GMT-0800 (Pacific Standard Time)

; increase Z
G91 ; relative positioning
G1 H2 Z5 F500 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home XY
var xTravel = move.axes[0].max - move.axes[0].min + 5 ; calculate how far X can travel plus 5mm
var yTravel = move.axes[1].max - move.axes[1].min + 5 ; calculate how far Y can travel plus 5mm
G91 ; relative positioning
G1 H1 X{var.xTravel} Y{var.yTravel} F1000 ; coarse home
G1 H1 X{var.xTravel} F1000 ; coarse home in the +X direction
G1 H1 Y{var.yTravel} F1000 ; coarse home in the +Y direction
G1 X-5 Y-5 F1000 ; move back 5mm
G1 H1 X{var.xTravel} Y{var.yTravel} F300 ; fine home
G1 H1 X{var.xTravel} F300 ; fine home in the +X direction
G1 H1 Y{var.yTravel} F300 ; fine home in the +Y direction
G90 ; absolute positioning

; home Z
var zTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G91 ; relative positioning
G1 H1 Z{-var.zTravel} F200 ; coarse home in the -Z direction
G1 Z5 F200 ; move back 5mm
G1 H1 Z-10 F100 ; fine home in the -Z direction
G90 ; absolute positioning

M98 P"posz.g"

