; pause.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Fri Jan 30 2026 19:53:04 GMT-0800 (Pacific Standard Time)
; modified by Keaton Wescott
M83 ; relative extruder moves
G1 E-10 F3600 ; retract 10mm of filament
G91 ; relative positioning
G1 Z5 F360 ; lift Z by 5mm
G90 ; absolute positioning

; homing XY is better than going to center of build plate
G28 X Y
