; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Fri Jan 30 2026 19:53:04 GMT-0800 (Pacific Standard Time)

M116 P0 ; wait for tool temperatures to be reached
